apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-f5qu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-f5qu
    app.kubernetes.io/part-of: tkrw-pr712-0075-0021-app
  name: devfile-sample-f5qu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-f5qu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-f5qu
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0021-tenant/tkrw-pr712-0075-0021-app/devfile-sample-f5qu@sha256:bf327caa7764dcbdef1bd8c54fadf344b805a3a4b737d4d7fca37835a0107aa5
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
